// Hardcoded city lore for major cities. Falls back to AI for unknown cities.
export const CITY_FACTS: Record<string, string> = {
  mumbai: "Home to Dhobi Ghat — the world's largest open-air laundry, washing over 100,000 garments daily.",
  "new york": "Has its own dialect for pizza folding — and more Fortune 500 HQs than any city on Earth.",
  london: "The Underground 'Tube' has carried passengers since 1863, the world's oldest subway.",
  paris: "There are exactly 37 bridges crossing the Seine within the city limits.",
  tokyo: "More Michelin stars than any other city — over 200, year after year.",
  dubai: "The Burj Khalifa is so tall you can watch the sunset twice from different floors.",
  sydney: "The Opera House's roof is covered in over a million Swedish-made tiles.",
  berlin: "Has nine times more bridges than Venice — 1,700 of them, in fact.",
  cairo: "The only one of the seven ancient wonders still standing sits on its outskirts.",
  singapore: "One of only three city-states left in the world, and the only island one.",
  istanbul: "The only city in the world that straddles two continents — Europe and Asia.",
  "los angeles": "More museums per capita than any other US city, and 75 micro-climates.",
  "san francisco": "Fortune cookies were invented here — not in China — at the Japanese Tea Garden.",
  chicago: "The Chicago River is dyed bright green every St. Patrick's Day since 1962.",
  toronto: "Officially the most multicultural city on Earth — over half its residents were born abroad.",
  "mexico city": "Built atop a drained lake, it sinks roughly an inch every year.",
  "rio de janeiro": "Christ the Redeemer is struck by lightning around four times a year.",
  "buenos aires": "Home to more bookstores per capita than any other city in the world.",
  moscow: "The Moscow Metro stations are sometimes called 'palaces for the people.'",
  beijing: "The Forbidden City has exactly 9,999 rooms — one short of the heavenly 10,000.",
  shanghai: "The Maglev train hits 268 mph between downtown and Pudong airport.",
  "hong kong": "Has more skyscrapers than any other city — over 550 buildings above 150m.",
  bangkok: "Its full ceremonial name has 168 letters — the longest place name on Earth.",
  delhi: "Hosts seven historical cities layered on top of each other across millennia.",
  bengaluru: "Known as the Garden City for its parks, but now also India's Silicon Valley.",
  hyderabad: "The Charminar's four minarets supposedly inspired the four-tower mosque blueprint.",
  kolkata: "The first city in Asia to have an underground metro railway.",
  chennai: "Marina Beach is the second-longest urban beach in the world.",
  amsterdam: "There are more bicycles than residents — about 880,000 of them.",
  rome: "Roughly €1 million in coins is tossed into the Trevi Fountain each year.",
  barcelona: "La Sagrada Família has been under construction since 1882 — and still isn't done.",
  madrid: "The geographical centre of Spain is marked in Puerta del Sol with a small stone.",
  vienna: "Sigmund Freud's couch sits exactly where he left it in his old apartment.",
  prague: "The Astronomical Clock has been keeping time since 1410 — the oldest still working.",
  athens: "There are an estimated 6,000 cafés in central Athens alone.",
  cape: "Table Mountain is one of the oldest mountains on Earth — six times older than the Himalayas.",
  johannesburg: "Built on top of the world's richest gold reef — 40% of all gold ever mined.",
  lagos: "One of the fastest-growing cities in the world — adding 77 people every hour.",
  nairobi: "The only world capital with a national park inside its city limits.",
  seoul: "Has the world's fastest internet — and the fastest 5G rollout.",
  jakarta: "Sinking faster than any major city on Earth — up to 25cm per year in places.",
  manila: "The most densely populated city in the world by some measurements.",
  "kuala lumpur": "The Petronas Towers' Skybridge is the world's highest two-story bridge.",
  doha: "The skyline didn't exist 30 years ago — almost every tower is post-2005.",
  "abu dhabi": "Sheikh Zayed Mosque holds the world's largest hand-knotted carpet.",
  riyadh: "The Kingdom Centre's sky-bridge sits 300 meters above the desert floor.",
  "tel aviv": "Has the largest collection of Bauhaus architecture in the world.",
  zurich: "Tap water here is so clean it's drawn straight from Alpine springs.",
  geneva: "Hosts the headquarters of more international organisations than any other city.",
  oslo: "The Nobel Peace Prize is the only Nobel awarded here, not in Stockholm.",
  stockholm: "Built across 14 islands connected by 57 bridges.",
  copenhagen: "Aims to be the world's first carbon-neutral capital by 2025.",
  helsinki: "Has more saunas than cars — about 3.3 million across Finland.",
  dublin: "Half of Ireland's population lives within 100km of the city centre.",
  edinburgh: "The first ever UNESCO City of Literature.",
  lisbon: "Older than Rome — by about 400 years.",
};

export function getCityFact(name: string): string | null {
  return CITY_FACTS[name.trim().toLowerCase()] ?? null;
}
